[build]
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

# Environment variables for email service
# Add these in your Netlify dashboard under Site settings > Environment variables
# EMAIL_USER = your-email@gmail.com
# EMAIL_PASS = your-app-password